#重置（清空）k8s集群
#--------------------------------------------------------------------
- hosts: etcd
#  remote_user: root
  tasks:
  - name: 删除容器
    tags: reset,reset-etcd
    shell: "docker rm -vf etcd"
    ignore_errors: yes
  - name: 删除目录
    tags: reset,reset-etcd
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/kubernetes
    - /tmp/etcd
    - /var/lib/etcd
- hosts: node,master
#  remote_user: root
  tasks:
  - name: 重置K8s
    tags: reset,reset-k8s
    shell: kubeadm reset -f
  - name: 重置iptables
    tags: reset,reset-k8s
    shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
  - name: 删除cni0网桥
    tags: reset,reset-k8s
    shell: ip link del cni0
    ignore_errors: yes
  - name: 删除flannel.1网桥
    tags: reset,reset-k8s
    shell: ip link del flannel.1
    ignore_errors: yes
  - name: 重启docker
    tags: reset,restart-docker
    shell: systemctl restart docker

#彻底清理docker与k8s
#--------------------------------------------------------------------
- hosts: node,master
#  remote_user: root
  tasks:
  - name: 停止docker
    tags: clear,stop-docker
    shell: systemctl stop docker
    ignore_errors: yes
  - name: 停止kubelet
    tags: clear,stop-kubelet
    shell: systemctl stop kubelet
    ignore_errors: yes
  - name: 彻底卸载k8s
    tags: clear,remove
    shell: yum -y remove kube*
  - name: 彻底卸载docker
    tags: clear,remove
    shell: "yum -y remove docker* && yum -y remove docker \
            docker-client \
            docker-client-latest \
            docker-common \
            docker-latest \
            docker-latest-logrotate \
            docker-logrotate \
            docker-selinux \
            docker-engine-selinux \
            docker-engine"
    ignore_errors: yes
  - name: 重启系统，等待80秒
    tags: clear,remove
    reboot: reboot_timeout=80
  - name: 清理docker卸载残留
    tags: clear,clear-docker
    shell: "rm -rf /etc/systemd/system/docker.service \
            /etc/systemd/system/docker.service.d \
            /var/lib/docker \
            /var/run/docker"
  - name: 清理k8s卸载残留
    tags: clear,clear-k8s
    shell: "for path in $(find / -name kube*); do rm -rf $path; done"
    ignore_errors: yes
